In [1]:
import pandas as pd
from pathlib import Path

In [13]:
RAW_DATA_DIR = Path('../raw_data/')
DATA_DIR = Path('../data/')

In [ ]:
# list here only the datasets we want to use in the modelling part
# use tuple with (Path, name of zipcode column in dataset)

datasets = [
    (DATA_DIR / '2018_2021' / 'disaster_trends_by_zip_2022.csv', 'ZIP'),
    (DATA_DIR / '2018_2021' / 'fair_plan2022.csv', 'ZIP Code'),
    (DATA_DIR / '2018_2021' / 'median_incomes_flat.csv', 'ZIP'),
    (DATA_DIR / '2018_2021' / 'percent_white_population_flat.csv', 'ZIP'),
    (DATA_DIR / '2018_2021' / 'policy_renewals.csv', 'ZIP Code'),
    (DATA_DIR / '2018_2021' / 'premiums_claims.csv', 'ZIP Code'),
    (DATA_DIR / '2018_2021' / 'Zillow_df_filtered.csv', 'zipcode')
]

datasets

[(WindowsPath('../data/2018_2021/disaster_trends_by_zip_2022.csv'), 'ZIP'),
 (WindowsPath('../data/2018_2021/fair_plan2022.csv'), 'ZIP Code'),
 (WindowsPath('../data/2018_2021/median_incomes_flat.csv'), 'ZIP'),
 (WindowsPath('../data/2018_2021/percent_white_population_flat.csv'), 'ZIP'),
 (WindowsPath('../data/2018_2021/policy_renewals.csv'), 'ZIP Code'),
 (WindowsPath('../data/2018_2021/premiums_claims.csv'), 'ZIP Code'),
 (WindowsPath('../data/2018_2021/Zillow_df_filtered.csv'), 'zipcode')]

In [64]:
# loading all datasets


renewals = pd.read_csv(DATA_DIR / '2018_2021' / 'policy_renewals.csv', index_col=0)
premiums = pd.read_csv(DATA_DIR / '2018_2021' / 'premiums_claims.csv', index_col=0)
fair = pd.read_csv(DATA_DIR / '2018_2021' / 'fair_plan2022.csv', index_col=0)
income = pd.read_csv(DATA_DIR / '2018_2021' / 'median_incomes_flat.csv', index_col=0).rename(columns={'ZIP': 'ZIP Code'})
race = pd.read_csv(DATA_DIR / '2018_2021' / 'percent_white_population_flat.csv', index_col=0).rename(columns={'ZIP': 'ZIP Code'})
housing = pd.read_csv(DATA_DIR / '2018_2021' / 'Zillow_df_filtered.csv', index_col=0).reset_index().rename(columns={'zipcode': 'ZIP Code'})
disasters = pd.read_csv(DATA_DIR / '2018_2021' / 'disaster_summary_by_zip.csv').rename(columns={'ZIP': 'ZIP Code'})

In [65]:
df = pd.merge(premiums, renewals, on='ZIP Code')
df = pd.merge(df, fair, on='ZIP Code')
df = pd.merge(df, income, on='ZIP Code')
df = pd.merge(df, race, on='ZIP Code')
df = pd.merge(df, housing, on='ZIP Code')
df = pd.merge(df, disasters, on='ZIP Code', how='left')

df

,ZIP Code,earned_premium,earned_exposure,fire_smoke_claims,fire_smoke_losses,growth_exposure,growth_premium,growth_fire_smoke_claims,growth_fire_smoke_losses,ratio_losses_to_premium,...,mean_2018_2021,percent_increase_2018_2021,Count_2022,Sum_1yr,Avg_3yr,Sum_3yr,Avg_5yr,Sum_5yr,Avg_10yr,Sum_10yr
0,90001,15005153,34015,126,4157573.0,0.217780,0.460404,0.283333,-0.352704,0.277076,...,4.475631e+05,31.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90002,15336299,31620,95,3793822.0,0.059597,0.266116,-0.357143,-0.595781,0.247375,...,4.377108e+05,35.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,90003,20549601,40859,133,4313440.0,0.069607,0.304515,1.333333,0.990114,0.209904,...,4.642817e+05,33.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90004,39605615,40942,48,3316605.0,0.208670,0.343416,-0.083333,0.725764,0.083741,...,1.261786e+06,20.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,90005,13665743,22208,16,885674.0,0.398915,0.383152,-0.142857,10.788063,0.064810,...,9.056021e+05,14.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,96145,32175843,16544,11,679976.0,0.251350,0.810447,-1.000000,-1.000000,0.021133,...,8.385008e+05,48.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1399,96146,14794212,8276,6,496222.0,0.292165,0.944032,-1.000000,-1.000000,0.033542,...,7.053495e+05,33.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1400,96148,5871798,3770,9,3092298.0,0.190595,0.714927,0.714286,287.782597,0.526636,...,6.563883e+05,47.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1401,96150,93760320,73114,898,23342320.0,0.176154,0.635895,15.122449,6.053769,0.248957,...,5.286650e+05,34.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1402,96161,116696623,64403,64,6821664.0,0.226978,0.828659,0.400000,0.442505,0.058456,...,7.580812e+05,46.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
# filling data related to disaster to 0
fields = ['Count_2022', 'Sum_1yr', 'Avg_3yr', 'Sum_3yr', 'Avg_5yr', 'Sum_5yr', 'Avg_10yr', 'Sum_10yr']
df[fields] = df[fields].fillna('0')

In [90]:
df

,ZIP Code,earned_premium,earned_exposure,fire_smoke_claims,fire_smoke_losses,growth_exposure,growth_premium,growth_fire_smoke_claims,growth_fire_smoke_losses,ratio_losses_to_premium,...,mean_2018_2021,percent_increase_2018_2021,Count_2022,Sum_1yr,Avg_3yr,Sum_3yr,Avg_5yr,Sum_5yr,Avg_10yr,Sum_10yr
0,90001,15005153,34015,126,4157573.0,0.217780,0.460404,0.283333,-0.352704,0.277076,...,4.475631e+05,31.65,0,0,0,0,0,0,0,0
1,90002,15336299,31620,95,3793822.0,0.059597,0.266116,-0.357143,-0.595781,0.247375,...,4.377108e+05,35.56,0,0,0,0,0,0,0,0
2,90003,20549601,40859,133,4313440.0,0.069607,0.304515,1.333333,0.990114,0.209904,...,4.642817e+05,33.98,0,0,0,0,0,0,0,0
3,90004,39605615,40942,48,3316605.0,0.208670,0.343416,-0.083333,0.725764,0.083741,...,1.261786e+06,20.65,0,0,0,0,0,0,0,0
4,90005,13665743,22208,16,885674.0,0.398915,0.383152,-0.142857,10.788063,0.064810,...,9.056021e+05,14.30,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,96145,32175843,16544,11,679976.0,0.251350,0.810447,-1.000000,-1.000000,0.021133,...,8.385008e+05,48.02,0,0,0,0,0,0,0,0
1399,96146,14794212,8276,6,496222.0,0.292165,0.944032,-1.000000,-1.000000,0.033542,...,7.053495e+05,33.89,0,0,0,0,0,0,0,0
1400,96148,5871798,3770,9,3092298.0,0.190595,0.714927,0.714286,287.782597,0.526636,...,6.563883e+05,47.46,0,0,0,0,0,0,0,0
1401,96150,93760320,73114,898,23342320.0,0.176154,0.635895,15.122449,6.053769,0.248957,...,5.286650e+05,34.01,0,0,0,0,0,0,0,0
1402,96161,116696623,64403,64,6821664.0,0.226978,0.828659,0.400000,0.442505,0.058456,...,7.580812e+05,46.35,0,0,0,0,0,0,0,0

In [91]:
df.sample(3)

,ZIP Code,earned_premium,earned_exposure,fire_smoke_claims,fire_smoke_losses,growth_exposure,growth_premium,growth_fire_smoke_claims,growth_fire_smoke_losses,ratio_losses_to_premium,...,mean_2018_2021,percent_increase_2018_2021,Count_2022,Sum_1yr,Avg_3yr,Sum_3yr,Avg_5yr,Sum_5yr,Avg_10yr,Sum_10yr
753,93657,27711900,35727,239,4591249.0,0.048136,0.337622,5.000000,5.683291,0.165678,...,284080.290588,32.66,0,0,0,0,0,0,0,0
588,93021,48842195,49898,132,3149594.0,0.040759,0.365762,-0.735294,0.208067,0.064485,...,717630.715265,19.17,0,0,0,0,0,0,0,0
514,92630,74371514,93766,191,5980467.0,0.062483,0.327766,-0.594595,-0.776135,0.080413,...,761005.017866,19.45,0,0,0,0,0,0,0,0

In [92]:
df.to_csv(DATA_DIR / '2018_2021' / 'consolidated_dataset.csv')